feat: enable github auth in local and preview environment
ubiquity/work.ubq.fi pull request #107
Opened 2024-10-07 03:28 UTC by zugdev

Resolves #82

2024-10-07 03:31 UTC, 0x4007 requested changes

2024-10-07 03:31 UTC, 0x4007 commented on src/home/rendering/render-github-login-button.ts
> +  let redirectTo = "https://work.ubq.fi";  // Default to production URL
There is also Devpool.directory

2024-10-07 03:38 UTC, zugdev commented on src/home/rendering/render-github-login-button.ts
> +  let redirectTo = "https://work.ubq.fi";  // Default to production URL
solved

2024-10-07 03:42 UTC, 0x4007 commented
Doesn't work

2024-10-07 04:32 UTC, zugdev commented
@0x4007 Can you please try again with console open? See if a msg pops up and redirect is correct.

2024-10-07 07:07 UTC, rndquu commented
@zugdev The issue is that cloudflare [preview deployment](https://github.com/ubiquity/work.ubq.fi/pull/107#issuecomment-2395824462) URLs redirect to `work.ubq.fi` after github oauth instead of the preview URL.

Example:
1. Open https://11352a0e.devpool-directory-ui.pages.dev/
2. Login with github
3. You'll be redirected to `work.ubq.fi` while the expected redirect URL is https://11352a0e.devpool-directory-ui.pages.dev/


Can't we simply use:
```js
  const { error } = await supabase.auth.signInWithOAuth({
    provider: "github",
    options: {
      scopes,
      redirectTo: window.location.origin,
    },
  });
```

2024-10-07 10:34 UTC, zugdev commented
> Example
> 
https://11352a0e.devpool-directory-ui.pages.dev/

So the problem is domain is different from what I expected! Can use wildcard for whatever is that beginning part of the domain.

> 
> Can't we simply use:
> ```js
>   const { error } = await supabase.auth.signInWithOAuth({
>     provider: "github",
>     options: {
>       scopes,
>       redirectTo: window.location.origin,
>     },
>   });
> ```
> 

According to [this discussion](https://github.com/supabase/supabase/discussions/6088#discussioncomment-2468175)this doesn't work, though it's very old. I do have a solution in mind will push in a few hours.

2024-10-07 12:45 UTC, zugdev commented
It does not work unfortunately, I made a simple deployment to test it: https://supabase-test-laqua7nr8-zugs-projects-e51b52e0.vercel.app

2024-10-07 13:25 UTC, zugdev commented
@rndquu @0x4007 According to [docs](https://supabase.com/docs/guides/auth/redirect-urls#use-wildcards-in-redirect-urls), you guys need to go into Supabase dashboard allow list and add all URLs you want to be able to redirect to. I've set up a test project to check it out and it should look something like this for you:

![image](https://github.com/user-attachments/assets/6b83a284-482e-4c85-81c7-212f1c95d53c)

![image](https://github.com/user-attachments/assets/ad3bedb6-815a-434f-b0c5-3e1a8cda5a39)

Use strict URL for the prod environment use wildcard for urls where a commit/deploy ID can come in some part  of the domain, as I did in: `https://**.devpool-directory-ui.pages.dev`

2024-10-07 13:42 UTC, zugdev commented
Because of the auth token the allowed redirect list should actually be:

`https://**.devpool-directory-ui.pages.dev/**` with the wildcard at the end. It is very important.

I think the allowed list would be close to:

`https://**.devpool-directory-ui.pages.dev/**` 
`https://devpool-directory-ui.pages.dev/**` 
`https://devpool.directory/**` 
`http://localhost:8080/**`

Set the default site URL to be prod so it can be strict and not allow wildcards.

2024-10-07 13:47 UTC, zugdev commented
After setting that using `window.location.href` should work! You can hypothetically try it out with my demo at:

1. https://supabase-test-beta.vercel.app
2. [supabase-test-git-master-zugs-projects-e51b52e0.vercel.app](https://supabase-test-git-master-zugs-projects-e51b52e0.vercel.app/)
3. [supabase-test-d7wua39up-zugs-projects-e51b52e0.vercel.app](https://supabase-test-d7wua39up-zugs-projects-e51b52e0.vercel.app/)

2024-10-07 13:53 UTC, rndquu commented
@zugdev Added

<img width="950" alt="Screenshot 2024-10-07 at 16 50 55" src="https://github.com/user-attachments/assets/1d7a9379-91d9-4830-89b8-e1c0585f7e8e">

2024-10-07 13:55 UTC, rndquu commented
@zugdev Preview deployment [failed](https://github.com/ubiquity/work.ubq.fi/actions/runs/11216992647/job/31177521722) due to rate limits, let's wait some time

2024-10-07 15:11 UTC, rndquu approved these changes
Works fine

2024-10-08 07:34 UTC, 0x4007 approved these changes

2024-10-08 07:34 UTC, merged