feat: fix live reload
ubiquity/work.ubq.fi pull request #165
Opened 2024-11-13 00:27 UTC by zugdev

Resolves #164

2024-11-14 14:10 UTC, 0x4007 requested changes

2024-11-14 14:10 UTC, 0x4007 commented on package.json
> +    "start": "concurrently \"yarn start-wrangler\" \"yarn watch\"",
```suggestion
    "start": "run-s start-wrangler watch",
```

We use npm-run-all for exactly situations like these

2024-11-14 14:10 UTC, 0x4007 commented on package.json
> +    "concurrently": "^9.1.0",
```suggestion
```
Remove and uninstall so lock file is up to date

2024-11-14 20:04 UTC, zugdev commented on package.json
> +    "start": "concurrently \"yarn start-wrangler\" \"yarn watch\"",
gotta use run-p actually

2024-11-18 09:20 UTC, 0x4007 approved these changes

2024-11-18 09:20 UTC, merged