feat: use daemon-pricing
ubiquity/work.ubq.fi pull request #182
Opened 2024-12-04 19:40 UTC by zugdev

use daemon pricing instead of assistive pricing worker

2024-12-05 03:49 UTC, 0x4007 requested changes
Collaborators only should match our org settings

2024-12-05 13:30 UTC, zugdev commented
I believe it does match
https://github.com/ubiquity/.ubiquity-os/blob/f94809ffc2b3934ff8b8a0035ed47eea56e43f54/.github/.ubiquity-os.config.yml#L32-L63

2024-12-06 17:11 UTC, 0x4007 commented
Oh I confused line 18 required labels to start!

2024-12-06 17:11 UTC, 0x4007 approved these changes

2024-12-06 17:11 UTC, merged