Fix #84: Hide Unauthorized issues
ubiquity/work.ubq.fi pull request #85
Opened 2024-08-26 12:17 UTC by ahmed-1026

Close newly created or edited issues if they are not from Authorized bots

Resolves #84

2024-08-26 13:10 UTC, Keyrxng requested changes
@ahmed-1026 thanks for the PR.

The logic should be embedded into the UI not as a workflow. 

See [`render-github-issues.ts`](https://github.com/ubiquity/work.ubq.fi/blob/development/src/home/rendering/render-github-issues.ts) for one place that might be used to stop the unauthorized issues from rendering. 

The backend effectively deletes any unauthorized issues once every hour, this PR aims to ensure that during that hour nothing can slip through.

2024-08-26 13:56 UTC, ahmed-1026 commented
My bad,
working on it.

2024-08-26 18:27 UTC, Keyrxng requested changes
Is it possible for you to provide some kind of QA in the form of screenshot, video or otherwise?

Typically PRs always come with some kind of visual proof that the spec has been achieved if possible, we can let it slide for this task but for future contributions please keep this in mind

2024-08-26 18:27 UTC, Keyrxng commented on .github/workflows/hide-issues.yml
Please remove this file if not being used

2024-08-26 19:12 UTC, ahmed-1026 commented
> Is it possible for you to provide some kind of QA in the form of screenshot, video or otherwise?
> 
> Typically PRs always come with some kind of visual proof that the spec has been achieved if possible, we can let it slide for this task but for future contributions please keep this in mind

![image](https://github.com/user-attachments/assets/d0a48f4a-37fc-4941-b649-c16bc320e07a)
This code snippet check for the id of creater, if it is in the list then it will proceed, otherwise skip.

2024-08-27 08:11 UTC, ahmed-1026 commented
I have updated working, now when issue are rendering it will check if user(creater) of issue is in the list or not.
![image](https://github.com/user-attachments/assets/a573ccd3-579c-4e74-9e6d-ff1a027dd92d)
I have request to list valid users in the list in line 17 of src/home/rendering/render-github-issues.ts

2024-08-27 09:42 UTC, Keyrxng commented
@ahmed-1026 thanks for the screenshots but what I meant was a screenshot or QA of the actual UI demonstrating the implemented changes. Reviewers can see the changes made to the codebase no problem but seeing the effect the code has requires a reviewer to pull, spin things up locally and find the path needed to trigger it.

It's expected a contributor will have already tested their work to prove it works (to themselves) so grabbing a screenshot at that point is ideal.

---

@0x4007 the implementation here uses the `app_slug` for verifying it's an authorized issue, this seems appropriate although would it be preferred to use the bot userId? We don't have the perk of knowing installs here so it's either or

2024-08-27 10:16 UTC, ahmed-1026 commented
> @ahmed-1026 thanks for the screenshots but what I meant was a screenshot or QA of the actual UI demonstrating the implemented changes. Reviewers can see the changes made to the codebase no problem but seeing the effect the code has requires a reviewer to pull, spin things up locally and find the path needed to trigger it.
> 
> It's expected a contributor will have already tested their work to prove it works (to themselves) so grabbing a screenshot at that point is ideal.
> 
> @0x4007 the implementation here uses the `app_slug` for verifying it's an authorized issue, this seems appropriate although would it be preferred to use the bot userId? We don't have the perk of knowing installs here so it's either or

@Keyrxng Thanks for review.
I understand that but for that I have to add an unauthorized issue which I can not.

2024-08-27 10:20 UTC, 0x4007 commented
Always use user id, not app name.

2024-08-27 10:32 UTC, ahmedraza1026 commented
I got a conflict that's why I used name instead of id
![image](https://github.com/user-attachments/assets/8cf9215a-db1d-4060-88c1-d4de1bf076cc)
No id is matching with the provided ids.

2024-08-28 03:20 UTC, 0x4007 commented
Strange I assumed that the app id would work in place of the user ID. @Keyrxng any idea? Otherwise we will need to default to app name which doesn't seem right.

2024-08-28 09:47 UTC, Keyrxng commented
This was how I did it in my quick fix PR (logic was force-pushed removed so no longer exists in the PR). 

To use the app_id I'm sure we'd need to be able to check the installs, so it's either the bot userId or the app_slug we need to use in this case unless we add support for official install checking


```ts
    if (isBot && userId !== 113181824 && userId !== 76412717 && userId !== 165700353 && userId !== 133917611) {
      continue;
    }
```

2024-09-03 20:27 UTC, Keyrxng commented
@ahmed-1026 could you use the botId to filter instead of the app_slug please and I will merge this after review. So this would be the `user.id` of the bot which posts tasks to the repo, thanks.

2024-10-03 22:41 UTC, closed without merging